name: Build Docker Container

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker image name (e.g. my-image:latest)'
        required: true
        default: 'streamlit-app-trident-serve-v4.2'
      dockerhub_repo:
        description: 'Docker Hub repository (e.g. myuser/myrepo:tag)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ github.event.inputs.image_name }} .
          docker image ls

      - name: Log in to Docker Hub
        if: ${{ github.event.inputs.dockerhub_repo != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push Docker image to Docker Hub
        if: ${{ github.event.inputs.dockerhub_repo != '' }}
        run: |
          docker tag ${{ github.event.inputs.image_name }} ${{ github.event.inputs.dockerhub_repo }}/${{ github.event.inputs.image_name }}
          docker push ${{ github.event.inputs.dockerhub_repo }}/${{ github.event.inputs.image_name }}

      - name: Save Docker image to tar file
        run: |
          docker save ${{ github.event.inputs.image_name }} -o image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.image_name }}-docker-image
          path: image.tar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.image_name }}
          name: ${{ github.event.inputs.image_name }}
          body: |
            The Docker image was built by this workflow run.
            You can download the image tarball from the workflow run's artifacts here:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}